### ISSUE TITLE
Will you open source code in the future?

### ISSUE THREAD

**Issue by gaojunbin** [za-cheng/PM-PMVS#2]
Hi,
It was a great work. But will you open source code? It seems that seven months have passed.

**Comment by za-cheng** [comment]
Hi,

I'm sorry but due to a covid lockdown here in Canberra I haven't been able to maintain this repository as promised. I should be able to make an initial push by early November if my office reopens as planned by then.

Again apologies for the delay.

Thanks
Z

**Comment by franmts** [comment]
Hello Ziang Cheng,

Hope this finds you well.

I have just read your other paper, amazing work on "One Ring to Rule Them
All: a simple solution to multi-view 3D-Reconstruction of shapes with
unknown BRDF via a small Recurrent ResNet".

Do you intend on publishing this source code soon as well?

Best regards,

*Francisco Toledo*

**Comment by za-cheng** [comment]
Thanks very much Francisco, 

Yes that's the plan. If my university does not open this month I will rewrite project codes and publish them here by the end of November.

**Comment by franmts** [comment]
Nice! Looking forward to test it.

*Francisco Toledo*
